on: push

name: deploy
jobs:
    deploy:
        name: deploy to cluster
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: build and push to docker
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password-stdin: ${{ secrets.DOCKER_PASSWORD }}
                  tag_with_ref: true
                  tag_with_sha: true
                  tags: jaimenavarrete/prueba-gha:latest, jaimenavarrete/prueba-gha:${{ github.sha }}
